/**
 * How much does this text look like real prose in a given language?
 *
 * Three channels, in order of how much they are trusted:
 *
 *   1. word list   the word is one of the language's most frequent - score 1
 *   2. bigrams     the spelling is plausible for the language - score 0..1
 *   3. structure   a rule that is near-decisive on its own, applied as a floor
 *
 * The bigram channel is what the word list cannot do. A stopword list can say
 * "this is not gibberish" but it cannot say "this is Hebrew" about any word it
 * has never seen, and that is most of the language. `לדוגמא` is not a stopword,
 * so under a list-only scorer `ksudnt` is undetectable.
 *
 * Both channels are generated by scripts/build-model.mjs and live in
 * layouts/<lang>/model.json. Nothing here is tuned by hand at runtime.
 */

import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { LAYOUTS_DIR } from './layout.mjs';

const BOUNDARY = 0;
const STRUCTURAL_FLOOR = 0.15; // what a near-decisive structural tell caps a token at
const MAX_TOKEN_WEIGHT = 10;   // one very long token must not outvote a sentence

export function loadModel(lang, { layoutsDir = LAYOUTS_DIR } = {}) {
  const file = join(layoutsDir, lang, 'model.json');
  if (!existsSync(file)) {
    throw new Error(`kbfix: no scoring model for "${lang}" (expected ${file}). Run: node scripts/build-model.mjs --lang ${lang}`);
  }
  return JSON.parse(readFileSync(file, 'utf8'));
}

/**
 * Build a scorer for one language.
 *
 * `structural` is a predicate that returns true when a token carries a tell so
 * strong it should cap the token's score regardless of the other channels. For
 * Hebrew that is a final form away from the end of a word; for English it is a
 * run of three or more letters with no vowel. Both were proven in practice
 * before the bigram channel existed, so they stay as a backstop.
 */
export function makeScorer(model, { letters, structural }) {
  const words = new Set(model.words);
  const alphabet = [...model.alphabet];
  const n = alphabet.length + 1;
  const index = new Map(alphabet.map((ch, i) => [ch, i + 1]));
  const { logp, calib } = model;
  const span = calib.hi - calib.lo;

  function bigramScore(token) {
    let prev = BOUNDARY;
    let sum = 0;
    let steps = 0;
    for (const ch of token) {
      const cur = index.get(ch);
      if (cur === undefined) continue;
      sum += logp[prev * n + cur];
      prev = cur;
      steps += 1;
    }
    if (steps === 0) return 0;
    sum += logp[prev * n + BOUNDARY];
    const mean = sum / (steps + 1);
    if (span <= 0) return 0;
    return clamp01((mean - calib.lo) / span);
  }

  function tokenize(text) {
    const out = [];
    let cur = '';
    for (const ch of text.toLowerCase()) {
      if (letters.has(ch)) cur += ch;
      else if (cur) { out.push(cur); cur = ''; }
    }
    if (cur) out.push(cur);
    return out;
  }

  /** 0..1 over the whole text, weighted by token length. */
  function score(text) {
    const toks = tokenize(text);
    if (toks.length === 0) return 0;
    let total = 0;
    let weight = 0;
    for (const t of toks) {
      let s = words.has(t) ? 1 : bigramScore(t);
      if (structural(t)) s = Math.min(s, STRUCTURAL_FLOOR);
      const w = Math.min(t.length, MAX_TOKEN_WEIGHT);
      total += s * w;
      weight += w;
    }
    return weight === 0 ? 0 : clamp01(total / weight);
  }

  score.tokenize = tokenize;
  score.explain = (text) => tokenize(text).map((t) => ({
    token: t,
    inWords: words.has(t),
    bigram: round(bigramScore(t)),
    structural: structural(t),
  }));
  return score;
}

/** A final form anywhere but the end of a word does not happen in real Hebrew. */
export function misplacedFinalForm(finalForms) {
  return (token) => {
    for (let i = 0; i < token.length - 1; i += 1) if (finalForms.has(token[i])) return true;
    return false;
  };
}

/** Three or more letters with no vowel is near-impossible in English. */
export function vowellessRun(vowels) {
  return (token) => {
    if (token.length < 3) return false;
    for (const ch of token) if (vowels.has(ch)) return false;
    return true;
  };
}

/**
 * The structural rule a layout declares, or none.
 *
 * A language that declares neither `finalForms` nor `vowels` (Russian, whose
 * consonant clusters are perfectly normal and whose alphabet has no positional
 * variants) simply relies on the word list and the bigram model.
 */
export function structuralRuleFor(L) {
  if (L.finalForms.size > 0) return misplacedFinalForm(L.finalForms);
  if (L.vowels.size > 0) return vowellessRun(L.vowels);
  return () => false;
}

const clamp01 = (x) => (x < 0 ? 0 : x > 1 ? 1 : x);
const round = (x) => Math.round(x * 100) / 100;
